owner: sirogamichandayo
repo: my-upptime

sites:
  - name: AtCoderDatabase
    url: https://atcoder-db.sirogami.com/
  - name: ユーザーごとのアルゴリズムレーティング取得
    url: https://data.ac-predictor.com/ratings/algorithm.json
  - name: ユーザーごとのヒューリスティックレーティング取得
    url: https://data.ac-predictor.com/ratings/heuristic.json
  - name: 各ユーザーのアルゴリズムコンテスト履歴取得
    url: https://atcoder.jp/users/sirogamichandayo/history/json
  - name: 各ユーザーのヒューリスティックコンテスト履歴取得
    url: https://atcoder.jp/users/sirogamichandayo/history/json?contestType=heuristic
  - name: 提出データ取得
    url: https://kenkoooo.com/atcoder/atcoder-api/v3/from/9223372036854775807
  - name: 問題一覧取得
    url: https://kenkoooo.com/atcoder/resources/problems.json
  - name: 問題モデル取得
    url: https://kenkoooo.com/atcoder/resources/problem-models.json
  - name: コンテスト情報取得
    url: https://atcoder.jp/api/contests/abc001

status-website:
  baseUrl: /my-upptime
  # If you use a custom domain, comment out the baseUrl line and uncomment the cname line below:
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: My Uptime
  introTitle: "My Status"
  introMessage: "This is the status page."
  navbar:
    - title: Status
      href: /
    - title: GitHub (Upptime)
      href: https://github.com/sirogamichandayo/my-upptime
    - title: GitHub (AtCoderDatabase)
      href: https://github.com/sirogamichandayo/AtCoderDatabase
